<a href="https://colab.research.google.com/github/nanduri19/Data-Science-Project-Using-Gold-And-Bitcoin/blob/main/5_Gold_data_Model_Implementation(GRU_and_Bi_GRU).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd_Price_Of_Historicaldata
import numpy as mu_Price_Of_Historicaldata
import warnings as rw_Price_Of_Historicaldata
rw_Price_Of_Historicaldata.filterwarnings("ignore")

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
GOld_Price_Of_Historicaldata = pd_Price_Of_Historicaldata.read_csv("/content/drive/MyDrive/Gold_final_data.csv")
GOld_Price_Of_Historicaldata.replace([mu_Price_Of_Historicaldata.inf, -mu_Price_Of_Historicaldata.inf], mu_Price_Of_Historicaldata.nan, inplace=True)
GOld_Price_Of_Historicaldata.fillna(999, inplace=True)
print("Shape details: ",GOld_Price_Of_Historicaldata.shape)
print("Columns details: ",GOld_Price_Of_Historicaldata.columns)
GOld_Price_Of_Historicaldata

Shape details:  (4999, 2)
Columns details:  Index(['Date', 'Price'], dtype='object')

            Date  Price
0     03/11/2023  999.0
1     02/11/2023  999.0
2     01/11/2023  999.0
3     31/10/2023  999.0
4     30/10/2023  999.0
...          ...    ...
4994  09/01/2004  426.8
4995  08/01/2004  424.4
4996  07/01/2004  422.3
4997  06/01/2004  423.2
4998  05/01/2004  424.8

[4999 rows x 2 columns]

In [4]:
GOld_Price_Of_Historicaldata

            Date  Price
0     03/11/2023  999.0
1     02/11/2023  999.0
2     01/11/2023  999.0
3     31/10/2023  999.0
4     30/10/2023  999.0
...          ...    ...
4994  09/01/2004  426.8
4995  08/01/2004  424.4
4996  07/01/2004  422.3
4997  06/01/2004  423.2
4998  05/01/2004  424.8

[4999 rows x 2 columns]

In [5]:
import tensorflow as txttflo
from keras.layers import Dense as txttdnse
from keras.layers import GRU as txttgrunt
from sklearn.metrics import r2_score as txtr2scre
from sklearn.metrics import mean_squared_error as txtrmeaser
from sklearn.metrics import mean_absolute_error as txtrmeasqr
from sklearn.model_selection import train_test_split as txtrtsplt
from sklearn.preprocessing import MinMaxScaler as txtrtmnmxsler
from tensorflow.keras.layers import Bidirectional as price_of_histbidirct

In [6]:
def His_SEGFn(txtIpXts_se_His, txtIpXts_n_His):
    vax_txtIpXts, vay_txtIpXts = [], []

    for RRr in range(len(txtIpXts_se_His)):
        Ad_txtIp = RRr + txtIpXts_n_His
        if Ad_txtIp > len(txtIpXts_se_His) - 1:
            break
        x_txtIpXts, y_txtIpXts = txtIpXts_se_His[RRr:Ad_txtIp], txtIpXts_se_His[Ad_txtIp]
        vax_txtIpXts.append(x_txtIpXts)
        vay_txtIpXts.append(y_txtIpXts)
    return mu_Price_Of_Historicaldata.array(vax_txtIpXts), mu_Price_Of_Historicaldata.array(vay_txtIpXts)

txtIpXts_n_His = 20

vax_txtIpXts_Tnn, vay_txtIpXts_Tnn = His_SEGFn(GOld_Price_Of_Historicaldata['Price'][:-200].tolist(), txtIpXts_n_His)
vax_txtIpXts_Tss, vay_txtIpXts_Tss = His_SEGFn(GOld_Price_Of_Historicaldata['Price'][-200:].tolist(), txtIpXts_n_His)
for total in range(len(vax_txtIpXts_Tss)):
    print(vax_txtIpXts_Tss[total], vay_txtIpXts_Tss[total])

[421.6 417.6 420.1 419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6
 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409. ] 410.1
[417.6 420.1 419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2
 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1] 407.0
[420.1 419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4
 414.7 414.2 410.7 409.7 412.6 409.  410.1 407. ] 407.6
[419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7
 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6] 406.5
[414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2
 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5] 406.8
[416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7
 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8] 407.5
[423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7
 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5] 406.0
[424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6
 409.  410.1 407.  407.6 406.5 406.8 407.5 406. ] 403.8
[419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.
 410.1 407.  407.6 406.5 406.8 407.5 406.  403.8] 400.4
[420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1
 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4] 401.4
[419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.
 407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4] 399.4
[415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6
 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4] 402.5
[421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5
 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5] 408.0
[420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8
 407.5 406.  403.8 400.4 401.4 399.4 402.5 408. ] 410.8
[414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5
 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8] 412.4
[414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.
 403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4] 410.0
[410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8
 400.4 401.4 399.4 402.5 408.  410.8 412.4 410. ] 405.4
[409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4
 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4] 409.6
[412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4
 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6] 410.0
[409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4
 402.5 408.  410.8 412.4 410.  405.4 409.6 410. ] 405.0
[410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5
 408.  410.8 412.4 410.  405.4 409.6 410.  405. ] 412.8
[407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.
 410.8 412.4 410.  405.4 409.6 410.  405.  412.8] 415.5
[407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8
 412.4 410.  405.4 409.6 410.  405.  412.8 415.5] 409.3
[406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4
 410.  405.4 409.6 410.  405.  412.8 415.5 409.3] 406.6
[406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.
 405.4 409.6 410.  405.  412.8 415.5 409.3 406.6] 406.7
[407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4
 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7] 405.2
[406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6
 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2] 401.2
[403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.
 405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2] 396.6
[400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.
 412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6] 397.9
[401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8
 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9] 402.3
[399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5
 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3] 403.0
[402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3
 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403. ] 402.1
[408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6
 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1] 394.8
[410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7
 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8] 394.7
[412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2
 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7] 396.5
[410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2
 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5] 394.4
[405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6
 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4] 393.7
[409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9
 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7] 389.8
[410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3
 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8] 389.0
[405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.
 402.1 394.8 394.7 396.5 394.4 393.7 389.8 389. ] 387.0
[412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1
 394.8 394.7 396.5 394.4 393.7 389.8 389.  387. ] 390.3
[415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8
 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3] 390.5
[409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7
 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5] 395.3
[406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5
 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3] 397.3
[406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4
 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3] 402.1
[405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7
 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1] 405.8
[401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8
 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8] 406.8
[396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.
 387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8] 404.4
[397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.
 390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4] 405.6
[402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3
 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6] 402.3
[403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5
 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3] 408.4
[402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3
 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4] 407.9
[394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3
 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9] 408.2
[394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1
 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2] 402.7
[396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8
 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7] 393.0
[394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8
 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393. ] 398.7
[393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4
 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7] 396.4
[389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6
 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4] 393.0
[389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3
 408.4 407.9 408.2 402.7 393.  398.7 396.4 393. ] 392.8
[387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4
 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8] 401.3
[390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9
 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3] 403.2
[390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2
 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2] 403.5
[395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7
 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5] 395.5
[397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.
 398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5] 395.5
[402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7
 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5] 394.5
[405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4
 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5] 395.7
[406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.
 392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7] 389.5
[404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8
 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5] 385.2
[405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3
 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2] 388.7
[402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2
 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7] 384.2
[408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5
 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2] 386.6
[407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5
 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6] 385.2
[408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5
 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2] 391.8
[402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5
 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8] 394.5
[393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7
 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5] 391.7
[398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5
 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7] 388.9
[396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2
 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9] 392.5
[393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7
 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5] 395.4
[392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2
 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4] 394.9
[401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6
 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9] 394.9
[403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2
 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9] 388.3
[403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8
 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3] 388.4
[395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5
 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4] 385.7
[395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7
 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7] 384.9
[394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9
 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9] 378.5
[395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5
 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5] 383.0
[389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4
 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383. ] 375.9
[385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9
 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9] 379.6
[388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9
 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6] 377.1
[384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3
 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1] 374.9
[386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4
 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9] 377.7
[385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7
 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7] 377.2
[391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9
 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2] 378.7
[394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5
 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7] 379.1
[391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.
 375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1] 388.4
[388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9
 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4] 393.8
[392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6
 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8] 391.8
[395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1
 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8] 387.5
[394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9
 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5] 387.5
[394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7
 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5] 387.1
[388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2
 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1] 385.9
[388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7
 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9] 399.1
[385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1
 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1] 396.6
[384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4
 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6] 395.7
[378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8
 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7] 393.9
[383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8
 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9] 391.4
[375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5
 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4] 398.3
[379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5
 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3] 401.2
[377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1
 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2] 401.6
[374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9
 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6] 398.3
[377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1
 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3] 400.5
[377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6
 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5] 407.7
[378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7
 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7] 420.9
[379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9
 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9] 420.7
[388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4
 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7] 423.7
[393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3
 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7] 419.8
[391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2
 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8] 416.3
[387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6
 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3] 422.5
[387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3
 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5] 428.8
[387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5
 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8] 428.3
[385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7
 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3] 422.8
[399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9
 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8] 417.1
[396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7
 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1] 422.2
[395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7
 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2] 416.9
[393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8
 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9] 417.4
[391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3
 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4] 420.0
[398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5
 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420. ] 417.6
[401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8
 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6] 412.7
[401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3
 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7] 411.3
[398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8
 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3] 407.1
[400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1
 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1] 402.6
[407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2
 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6] 399.6
[420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9
 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6] 395.6
[420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4
 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6] 401.0
[423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.
 417.6 412.7 411.3 407.1 402.6 399.6 395.6 401. ] 400.3
[419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6
 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3] 404.5
[416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7
 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5] 400.9
[422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3
 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9] 401.6
[428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1
 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6] 393.2
[428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6
 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2] 392.7
[422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6
 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7] 393.8
[417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6
 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8] 399.6
[422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.
 400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6] 396.8
[416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3
 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8] 395.5
[417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5
 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5] 396.1
[420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9
 401.6 393.2 392.7 393.8 399.6 396.8 395.5 396.1] 404.8
[417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6
 393.2 392.7 393.8 399.6 396.8 395.5 396.1 404.8] 399.3
[412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2
 392.7 393.8 399.6 396.8 395.5 396.1 404.8 399.3] 398.0
[411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7
 393.8 399.6 396.8 395.5 396.1 404.8 399.3 398. ] 410.3
[407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8
 399.6 396.8 395.5 396.1 404.8 399.3 398.  410.3] 412.8
[402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6
 396.8 395.5 396.1 404.8 399.3 398.  410.3 412.8] 416.5
[399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8
 395.5 396.1 404.8 399.3 398.  410.3 412.8 416.5] 410.8
[395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5
 396.1 404.8 399.3 398.  410.3 412.8 416.5 410.8] 414.2
[401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5 396.1
 404.8 399.3 398.  410.3 412.8 416.5 410.8 414.2] 410.7
[400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5 396.1 404.8
 399.3 398.  410.3 412.8 416.5 410.8 414.2 410.7] 407.0

In [7]:
srtxtrtmnmxsler = txtrtmnmxsler()
vax_txtIpXts_Tnn_sca = srtxtrtmnmxsler.fit_transform(vax_txtIpXts_Tnn)
vax_txtIpXts_Tss_sca = srtxtrtmnmxsler.transform(vax_txtIpXts_Tss)

txtIpXtrrshped = vax_txtIpXts_Tnn_sca.reshape((vax_txtIpXts_Tnn_sca.shape[0], 1, vax_txtIpXts_Tnn_sca.shape[1]))
txtIpXtsrshped = vax_txtIpXts_Tss_sca.reshape((vax_txtIpXts_Tss_sca.shape[0], 1, vax_txtIpXts_Tss_sca.shape[1]))

 changing both Optimizer and activation function

GRU

In [8]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(txttgrunt(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2])))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse', metrics=['accuracy'])

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step
Optimizer is: adam, activation is: relu
R-squared: -799.2500902277867
Mean Squared Error: 110766.95313428748
Mean Absolute Error: 332.58425654093423
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step
Optimizer is: adam, activation is: tanh
R-squared: -825.8933313044585
Mean Squared Error: 114454.78856439056
Mean Absolute Error: 338.1374671808878
---

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7db3fc6ec160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -885.482666172852
Mean Squared Error: 122702.87143657357
Mean Absolute Error: 350.12032280815976
---

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7db3eeede320> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Optimizer is: sgd, activation is: relu
R-squared: -654058.5362383708
Mean Squared Error: 90531926.05942407
Mean Absolute Error: 2260.2064354112413
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -428.3521219825101
Mean Squared Error: 59428.95471615186
Mean Absolute Error: 196.15754910786947
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -131.63879767387857
Mean Squared Error: 18359.255019326214
Mean Absolute Error: 121.92483983357748
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: -710.2947468183686
Mean Squared Error: 98454.16182717151
Mean Absolute Error: 313.4263982009888
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -805.9729869397953
Mean Squared Error: 111697.50571293668
Mean Absolute Error: 334.0608397038778
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -861.144730422456
Mean Squared Error: 119334.12581371202
Mean Absolute Error: 345.3084183883667
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1166.1733307203806
Mean Squared Error: 161554.7879372242
Mean Absolute Error: 401.76656913235735
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1166.0232891977348
Mean Squared Error: 161534.01987670155
Mean Absolute Error: 401.7406351926861
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1166.2490519850537
Mean Squared Error: 161565.26892795166
Mean Absolute Error: 401.77962038856623
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1163.632661924904
Mean Squared Error: 161203.12019630813
Mean Absolute Error: 401.33066608130935
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1162.6624598728588
Mean Squared Error: 161068.8292708312
Mean Absolute Error: 401.1634395010273
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1162.5295768094022
Mean Squared Error: 161050.43620566072
Mean Absolute Error: 401.13920914418173
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Optimizer is: adamax, activation is: relu
R-squared: -851.9214227323788
Mean Squared Error: 118057.47779689131
Mean Absolute Error: 343.38119011773
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -870.1716287539762
Mean Squared Error: 120583.58774648214
Mean Absolute Error: 347.0840007230971
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -937.4578208058676
Mean Squared Error: 129897.03434600087
Mean Absolute Error: 360.24778981526697
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Optimizer is: nadam, activation is: relu
R-squared: -786.7841591678297
Mean Squared Error: 109041.47603862046
Mean Absolute Error: 329.97701565212674
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -826.0510564706066
Mean Squared Error: 114476.6201596633
Mean Absolute Error: 338.168193359375
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -921.9099075397435
Mean Squared Error: 127744.96338579075
Mean Absolute Error: 357.2434909269545
---

BiDirectional GRU

In [9]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(price_of_histbidirct(txttgrunt(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2]))))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse')

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 91ms/step
Optimizer is: adam, activation is: relu
R-squared: -765.2478714131493
Mean Squared Error: 106060.5217025451
Mean Absolute Error: 325.42883445739744
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step
Optimizer is: adam, activation is: tanh
R-squared: -566.5072520751287
Mean Squared Error: 78551.75520952581
Mean Absolute Error: 280.0825811258952
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -625.223927265127
Mean Squared Error: 86679.0485249448
Mean Absolute Error: 294.23481268141006
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step
Optimizer is: sgd, activation is: relu
R-squared: -6324787197209.611
Mean Squared Error: 875448082559233.2
Mean Absolute Error: 3052455.823715651
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -1022.7933246476698
Mean Squared Error: 141708.7840354575
Mean Absolute Error: 309.320599416097
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -626.9681249423473
Mean Squared Error: 86920.47238072293
Mean Absolute Error: 294.35676308525933
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: -419.89435047087676
Mean Squared Error: 58258.26871175174
Mean Absolute Error: 240.7842813364665
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -538.6405868349245
Mean Squared Error: 74694.57900878093
Mean Absolute Error: 273.1202002292209
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -625.177098879697
Mean Squared Error: 86672.56675426134
Mean Absolute Error: 294.22497177971735
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1166.1069976071396
Mean Squared Error: 161545.60641142953
Mean Absolute Error: 401.75515709222606
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1166.0416354958843
Mean Squared Error: 161536.55928728348
Mean Absolute Error: 401.7441031943821
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1167.3870522588893
Mean Squared Error: 161722.78571493868
Mean Absolute Error: 401.97563557735754
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1163.4994659373
Mean Squared Error: 161184.68381761006
Mean Absolute Error: 401.30776375419566
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1161.062396355628
Mean Squared Error: 160847.3558054867
Mean Absolute Error: 400.88889432569346
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1156.6013984622498
Mean Squared Error: 160229.88490404972
Mean Absolute Error: 400.1154258177016
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step
Optimizer is: adamax, activation is: relu
R-squared: -807.7119770458334
Mean Squared Error: 111938.20876055729
Mean Absolute Error: 334.326013086107
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -646.5415473503136
Mean Squared Error: 89629.73588349078
Mean Absolute Error: 299.2131165059408
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -792.6006325632474
Mean Squared Error: 109846.56565231069
Mean Absolute Error: 331.269888504876
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step
Optimizer is: nadam, activation is: relu
R-squared: -760.8415119948314
Mean Squared Error: 105450.61360863571
Mean Absolute Error: 324.4872777175903
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -567.2134773313379
Mean Squared Error: 78649.50767567613
Mean Absolute Error: 280.25722695244684
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -621.0744764797993
Mean Squared Error: 86104.70054762611
Mean Absolute Error: 293.2590821244982
---