<a href="https://colab.research.google.com/github/nanduri19/Data-Science-Project-Using-Gold-And-Bitcoin/blob/main/7_Gold_data_Model_Implementation(RNN_and_Bi_RNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd_Price_Of_Historicaldata
import numpy as mu_Price_Of_Historicaldata
import warnings as rw_Price_Of_Historicaldata
rw_Price_Of_Historicaldata.filterwarnings("ignore")

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
GOld_Price_Of_Historicaldata = pd_Price_Of_Historicaldata.read_csv("/content/drive/MyDrive/Gold_final_data.csv")
GOld_Price_Of_Historicaldata.replace([mu_Price_Of_Historicaldata.inf, -mu_Price_Of_Historicaldata.inf], mu_Price_Of_Historicaldata.nan, inplace=True)
GOld_Price_Of_Historicaldata.fillna(999, inplace=True)
print("Shape details: ",GOld_Price_Of_Historicaldata.shape)
print("Columns details: ",GOld_Price_Of_Historicaldata.columns)
GOld_Price_Of_Historicaldata

Shape details:  (4999, 2)
Columns details:  Index(['Date', 'Price'], dtype='object')

            Date  Price
0     03/11/2023  999.0
1     02/11/2023  999.0
2     01/11/2023  999.0
3     31/10/2023  999.0
4     30/10/2023  999.0
...          ...    ...
4994  09/01/2004  426.8
4995  08/01/2004  424.4
4996  07/01/2004  422.3
4997  06/01/2004  423.2
4998  05/01/2004  424.8

[4999 rows x 2 columns]

In [4]:
GOld_Price_Of_Historicaldata

            Date  Price
0     03/11/2023  999.0
1     02/11/2023  999.0
2     01/11/2023  999.0
3     31/10/2023  999.0
4     30/10/2023  999.0
...          ...    ...
4994  09/01/2004  426.8
4995  08/01/2004  424.4
4996  07/01/2004  422.3
4997  06/01/2004  423.2
4998  05/01/2004  424.8

[4999 rows x 2 columns]

In [5]:
import tensorflow as txttflo
from keras.layers import Dense as txttdnse
from keras.layers import SimpleRNN as txttsmprn
from sklearn.metrics import r2_score as txtr2scre
from sklearn.metrics import mean_squared_error as txtrmeaser
from sklearn.metrics import mean_absolute_error as txtrmeasqr
from sklearn.model_selection import train_test_split as txtrtsplt
from sklearn.preprocessing import MinMaxScaler as txtrtmnmxsler
from tensorflow.keras.layers import Bidirectional as price_of_histbidirct

In [6]:
def His_SEGFn(txtIpXts_se_His, txtIpXts_n_His):
    vax_txtIpXts, vay_txtIpXts = [], []

    for RRr in range(len(txtIpXts_se_His)):
        Ad_txtIp = RRr + txtIpXts_n_His
        if Ad_txtIp > len(txtIpXts_se_His) - 1:
            break
        x_txtIpXts, y_txtIpXts = txtIpXts_se_His[RRr:Ad_txtIp], txtIpXts_se_His[Ad_txtIp]
        vax_txtIpXts.append(x_txtIpXts)
        vay_txtIpXts.append(y_txtIpXts)
    return mu_Price_Of_Historicaldata.array(vax_txtIpXts), mu_Price_Of_Historicaldata.array(vay_txtIpXts)

txtIpXts_n_His = 20

vax_txtIpXts_Tnn, vay_txtIpXts_Tnn = His_SEGFn(GOld_Price_Of_Historicaldata['Price'][:-200].tolist(), txtIpXts_n_His)
vax_txtIpXts_Tss, vay_txtIpXts_Tss = His_SEGFn(GOld_Price_Of_Historicaldata['Price'][-200:].tolist(), txtIpXts_n_His)
for total in range(len(vax_txtIpXts_Tss)):
    print(vax_txtIpXts_Tss[total], vay_txtIpXts_Tss[total])

[421.6 417.6 420.1 419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6
 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409. ] 410.1
[417.6 420.1 419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2
 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1] 407.0
[420.1 419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4
 414.7 414.2 410.7 409.7 412.6 409.  410.1 407. ] 407.6
[419.5 414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7
 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6] 406.5
[414.6 416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2
 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5] 406.8
[416.6 423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7
 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8] 407.5
[423.4 424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7
 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5] 406.0
[424.5 419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6
 409.  410.1 407.  407.6 406.5 406.8 407.5 406. ] 403.8
[419.5 420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.
 410.1 407.  407.6 406.5 406.8 407.5 406.  403.8] 400.4
[420.  419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1
 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4] 401.4
[419.8 415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.
 407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4] 399.4
[415.6 421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6
 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4] 402.5
[421.2 420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5
 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5] 408.0
[420.4 414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8
 407.5 406.  403.8 400.4 401.4 399.4 402.5 408. ] 410.8
[414.7 414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5
 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8] 412.4
[414.2 410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.
 403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4] 410.0
[410.7 409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8
 400.4 401.4 399.4 402.5 408.  410.8 412.4 410. ] 405.4
[409.7 412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4
 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4] 409.6
[412.6 409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4
 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6] 410.0
[409.  410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4
 402.5 408.  410.8 412.4 410.  405.4 409.6 410. ] 405.0
[410.1 407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5
 408.  410.8 412.4 410.  405.4 409.6 410.  405. ] 412.8
[407.  407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.
 410.8 412.4 410.  405.4 409.6 410.  405.  412.8] 415.5
[407.6 406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8
 412.4 410.  405.4 409.6 410.  405.  412.8 415.5] 409.3
[406.5 406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4
 410.  405.4 409.6 410.  405.  412.8 415.5 409.3] 406.6
[406.8 407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.
 405.4 409.6 410.  405.  412.8 415.5 409.3 406.6] 406.7
[407.5 406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4
 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7] 405.2
[406.  403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6
 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2] 401.2
[403.8 400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.
 405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2] 396.6
[400.4 401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.
 412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6] 397.9
[401.4 399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8
 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9] 402.3
[399.4 402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5
 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3] 403.0
[402.5 408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3
 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403. ] 402.1
[408.  410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6
 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1] 394.8
[410.8 412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7
 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8] 394.7
[412.4 410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2
 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7] 396.5
[410.  405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2
 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5] 394.4
[405.4 409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6
 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4] 393.7
[409.6 410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9
 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7] 389.8
[410.  405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3
 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8] 389.0
[405.  412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.
 402.1 394.8 394.7 396.5 394.4 393.7 389.8 389. ] 387.0
[412.8 415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1
 394.8 394.7 396.5 394.4 393.7 389.8 389.  387. ] 390.3
[415.5 409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8
 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3] 390.5
[409.3 406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7
 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5] 395.3
[406.6 406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5
 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3] 397.3
[406.7 405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4
 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3] 402.1
[405.2 401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7
 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1] 405.8
[401.2 396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8
 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8] 406.8
[396.6 397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.
 387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8] 404.4
[397.9 402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.
 390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4] 405.6
[402.3 403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3
 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6] 402.3
[403.  402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5
 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3] 408.4
[402.1 394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3
 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4] 407.9
[394.8 394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3
 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9] 408.2
[394.7 396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1
 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2] 402.7
[396.5 394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8
 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7] 393.0
[394.4 393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8
 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393. ] 398.7
[393.7 389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4
 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7] 396.4
[389.8 389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6
 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4] 393.0
[389.  387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3
 408.4 407.9 408.2 402.7 393.  398.7 396.4 393. ] 392.8
[387.  390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4
 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8] 401.3
[390.3 390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9
 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3] 403.2
[390.5 395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2
 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2] 403.5
[395.3 397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7
 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5] 395.5
[397.3 402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.
 398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5] 395.5
[402.1 405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7
 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5] 394.5
[405.8 406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4
 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5] 395.7
[406.8 404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.
 392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7] 389.5
[404.4 405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8
 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5] 385.2
[405.6 402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3
 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2] 388.7
[402.3 408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2
 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7] 384.2
[408.4 407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5
 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2] 386.6
[407.9 408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5
 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6] 385.2
[408.2 402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5
 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2] 391.8
[402.7 393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5
 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8] 394.5
[393.  398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7
 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5] 391.7
[398.7 396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5
 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7] 388.9
[396.4 393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2
 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9] 392.5
[393.  392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7
 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5] 395.4
[392.8 401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2
 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4] 394.9
[401.3 403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6
 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9] 394.9
[403.2 403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2
 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9] 388.3
[403.5 395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8
 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3] 388.4
[395.5 395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5
 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4] 385.7
[395.5 394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7
 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7] 384.9
[394.5 395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9
 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9] 378.5
[395.7 389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5
 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5] 383.0
[389.5 385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4
 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383. ] 375.9
[385.2 388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9
 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9] 379.6
[388.7 384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9
 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6] 377.1
[384.2 386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3
 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1] 374.9
[386.6 385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4
 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9] 377.7
[385.2 391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7
 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7] 377.2
[391.8 394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9
 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2] 378.7
[394.5 391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5
 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7] 379.1
[391.7 388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.
 375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1] 388.4
[388.9 392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9
 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4] 393.8
[392.5 395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6
 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8] 391.8
[395.4 394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1
 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8] 387.5
[394.9 394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9
 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5] 387.5
[394.9 388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7
 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5] 387.1
[388.3 388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2
 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1] 385.9
[388.4 385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7
 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9] 399.1
[385.7 384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1
 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1] 396.6
[384.9 378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4
 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6] 395.7
[378.5 383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8
 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7] 393.9
[383.  375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8
 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9] 391.4
[375.9 379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5
 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4] 398.3
[379.6 377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5
 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3] 401.2
[377.1 374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1
 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2] 401.6
[374.9 377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9
 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6] 398.3
[377.7 377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1
 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3] 400.5
[377.2 378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6
 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5] 407.7
[378.7 379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7
 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7] 420.9
[379.1 388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9
 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9] 420.7
[388.4 393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4
 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7] 423.7
[393.8 391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3
 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7] 419.8
[391.8 387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2
 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8] 416.3
[387.5 387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6
 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3] 422.5
[387.5 387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3
 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5] 428.8
[387.1 385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5
 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8] 428.3
[385.9 399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7
 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3] 422.8
[399.1 396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9
 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8] 417.1
[396.6 395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7
 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1] 422.2
[395.7 393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7
 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2] 416.9
[393.9 391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8
 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9] 417.4
[391.4 398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3
 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4] 420.0
[398.3 401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5
 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420. ] 417.6
[401.2 401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8
 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6] 412.7
[401.6 398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3
 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7] 411.3
[398.3 400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8
 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3] 407.1
[400.5 407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1
 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1] 402.6
[407.7 420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2
 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6] 399.6
[420.9 420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9
 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6] 395.6
[420.7 423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4
 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6] 401.0
[423.7 419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.
 417.6 412.7 411.3 407.1 402.6 399.6 395.6 401. ] 400.3
[419.8 416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6
 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3] 404.5
[416.3 422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7
 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5] 400.9
[422.5 428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3
 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9] 401.6
[428.8 428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1
 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6] 393.2
[428.3 422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6
 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2] 392.7
[422.8 417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6
 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7] 393.8
[417.1 422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6
 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8] 399.6
[422.2 416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.
 400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6] 396.8
[416.9 417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3
 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8] 395.5
[417.4 420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5
 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5] 396.1
[420.  417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9
 401.6 393.2 392.7 393.8 399.6 396.8 395.5 396.1] 404.8
[417.6 412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6
 393.2 392.7 393.8 399.6 396.8 395.5 396.1 404.8] 399.3
[412.7 411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2
 392.7 393.8 399.6 396.8 395.5 396.1 404.8 399.3] 398.0
[411.3 407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7
 393.8 399.6 396.8 395.5 396.1 404.8 399.3 398. ] 410.3
[407.1 402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8
 399.6 396.8 395.5 396.1 404.8 399.3 398.  410.3] 412.8
[402.6 399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6
 396.8 395.5 396.1 404.8 399.3 398.  410.3 412.8] 416.5
[399.6 395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8
 395.5 396.1 404.8 399.3 398.  410.3 412.8 416.5] 410.8
[395.6 401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5
 396.1 404.8 399.3 398.  410.3 412.8 416.5 410.8] 414.2
[401.  400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5 396.1
 404.8 399.3 398.  410.3 412.8 416.5 410.8 414.2] 410.7
[400.3 404.5 400.9 401.6 393.2 392.7 393.8 399.6 396.8 395.5 396.1 404.8
 399.3 398.  410.3 412.8 416.5 410.8 414.2 410.7] 407.0

In [7]:
srtxtrtmnmxsler = txtrtmnmxsler()
vax_txtIpXts_Tnn_sca = srtxtrtmnmxsler.fit_transform(vax_txtIpXts_Tnn)
vax_txtIpXts_Tss_sca = srtxtrtmnmxsler.transform(vax_txtIpXts_Tss)

txtIpXtrrshped = vax_txtIpXts_Tnn_sca.reshape((vax_txtIpXts_Tnn_sca.shape[0], 1, vax_txtIpXts_Tnn_sca.shape[1]))
txtIpXtsrshped = vax_txtIpXts_Tss_sca.reshape((vax_txtIpXts_Tss_sca.shape[0], 1, vax_txtIpXts_Tss_sca.shape[1]))

 changing both Optimizer and activation function

RNN

In [8]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(txttsmprn(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2])))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse', metrics=['accuracy'])

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Optimizer is: adam, activation is: relu
R-squared: -993.7431741211515
Mean Squared Error: 137687.79522057474
Mean Absolute Error: 370.8429286750158
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
Optimizer is: adam, activation is: tanh
R-squared: -863.8670130714677
Mean Squared Error: 119710.93171262236
Mean Absolute Error: 345.8389622031318
---

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x794035334280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -888.7731956088426
Mean Squared Error: 123158.33145372848
Mean Absolute Error: 350.7729675165812
---

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x794035e6c700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Optimizer is: sgd, activation is: relu
R-squared: -4.2775977185054446e+21
Mean Squared Error: 5.920854890227609e+23
Mean Absolute Error: 91126559684.8879
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -2665.3779528936616
Mean Squared Error: 369067.8268619762
Mean Absolute Error: 545.4582620578341
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -711.0822614767585
Mean Squared Error: 98563.1660001465
Mean Absolute Error: 313.5264860237969
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: -1037.9183975284222
Mean Squared Error: 143802.3273657158
Mean Absolute Error: 379.0572650689549
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -902.2639064752574
Mean Squared Error: 125025.65387772601
Mean Absolute Error: 353.1566014281909
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -895.08614383116
Mean Squared Error: 124032.14083959382
Mean Absolute Error: 352.048428501553
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1166.3217125003316
Mean Squared Error: 161575.32626376304
Mean Absolute Error: 401.79240056150286
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1165.972038547583
Mean Squared Error: 161526.9259963849
Mean Absolute Error: 401.7315876073432
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1166.653652707805
Mean Squared Error: 161621.27190732316
Mean Absolute Error: 401.84921771481635
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1164.1883672509975
Mean Squared Error: 161280.03838296444
Mean Absolute Error: 401.4270358389368
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1163.5726289956822
Mean Squared Error: 161194.81071313674
Mean Absolute Error: 401.3212030831642
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1156.1157270049944
Mean Squared Error: 160162.66048483204
Mean Absolute Error: 400.0312061156167
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Optimizer is: adamax, activation is: relu
R-squared: -987.7785682123791
Mean Squared Error: 136862.20178268658
Mean Absolute Error: 369.73768409940936
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -930.1397607793072
Mean Squared Error: 128884.10198661157
Mean Absolute Error: 358.8652199088203
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -994.3954527136517
Mean Squared Error: 137778.0806365569
Mean Absolute Error: 371.0184340561761
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Optimizer is: nadam, activation is: relu
R-squared: -990.236900015334
Mean Squared Error: 137202.4728141199
Mean Absolute Error: 370.18632705595763
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -863.563284111566
Mean Squared Error: 119668.89094077142
Mean Absolute Error: 345.7785956997342
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -891.8222339119962
Mean Squared Error: 123580.36537406697
Mean Absolute Error: 351.37437003241644
---

BiDirectional RNN

In [9]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(price_of_histbidirct(txttsmprn(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2]))))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse')

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Optimizer is: adam, activation is: relu
R-squared: -978.5235514184801
Mean Squared Error: 135581.16473691122
Mean Absolute Error: 367.98574588351784
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step
Optimizer is: adam, activation is: tanh
R-squared: -623.3285418540712
Mean Squared Error: 86416.69795533965
Mean Absolute Error: 293.80457251654735
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -653.1152372026019
Mean Squared Error: 90539.63593183753
Mean Absolute Error: 300.7289785257975
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Optimizer is: sgd, activation is: relu
R-squared: -1931061214708.8887
Mean Squared Error: 267288650987000.44
Mean Absolute Error: 1690603.8528847927
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -708.2617295784504
Mean Squared Error: 98172.76089003308
Mean Absolute Error: 284.69835009256997
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -0.22777176411592115
Mean Squared Error: 169.94254560686028
Mean Absolute Error: 10.65326673719618
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: -875.3285022040404
Mean Squared Error: 121297.37855605285
Mean Absolute Error: 348.0464098909166
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -695.4097472791948
Mean Squared Error: 96393.84834955573
Mean Absolute Error: 308.4043861765332
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -696.8603487609325
Mean Squared Error: 96594.63396433578
Mean Absolute Error: 310.576714714898
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1166.0068401417338
Mean Squared Error: 161531.74307369036
Mean Absolute Error: 401.7375452380519
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1165.8851827760682
Mean Squared Error: 161514.90381820546
Mean Absolute Error: 401.7169764320801
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1165.7066250342737
Mean Squared Error: 161490.1886732044
Mean Absolute Error: 401.68625695261693
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1163.2814775503864
Mean Squared Error: 161154.510863265
Mean Absolute Error: 401.2715961835782
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1162.0687917383455
Mean Squared Error: 160986.65644606558
Mean Absolute Error: 401.06415405154644
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1148.4608713845084
Mean Squared Error: 159103.11042152275
Mean Absolute Error: 398.7048052289751
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Optimizer is: adamax, activation is: relu
R-squared: -976.2948042985358
Mean Squared Error: 135272.67176602912
Mean Absolute Error: 367.570785279274
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -722.9553705769424
Mean Squared Error: 100206.58739468081
Mean Absolute Error: 316.4028921424018
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -780.2420249910392
Mean Squared Error: 108135.94378238227
Mean Absolute Error: 328.67687993367514
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
Optimizer is: nadam, activation is: relu
R-squared: -968.2255696466618
Mean Squared Error: 134155.7652546418
Mean Absolute Error: 366.0466159481473
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -622.2636429780183
Mean Squared Error: 86269.29952910151
Mean Absolute Error: 293.55434711032444
---
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -652.8758360613548
Mean Squared Error: 90506.4991220869
Mean Absolute Error: 300.6746042548285
---