<a href="https://colab.research.google.com/github/nanduri19/Data-Science-Project-Using-Gold-And-Bitcoin/blob/main/8_Training_with_Gold_data_%26_testing_with_Bitcoin_data_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd_Price_Of_Historicaldata
import numpy as mu_Price_Of_Historicaldata
import warnings as rw_Price_Of_Historicaldata
rw_Price_Of_Historicaldata.filterwarnings("ignore")

In [2]:
from google.colab import drivey drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
GOld_Price_Of_Historicaldata = pd_Price_Of_Historicaldata.read_csv("/content/drive/MyDrive/Gold_final_data.csv")
GOld_Price_Of_Historicaldata.replace([mu_Price_Of_Historicaldata.inf, -mu_Price_Of_Historicaldata.inf], mu_Price_Of_Historicaldata.nan, inplace=True)
GOld_Price_Of_Historicaldata.fillna(999, inplace=True)
print("Shape details: ",GOld_Price_Of_Historicaldata.shape)
print("Columns details: ",GOld_Price_Of_Historicaldata.columns)
GOld_Price_Of_Historicaldata

Shape details:  (4999, 2)
Columns details:  Index(['Date', 'Price'], dtype='object')

            Date  Price
0     03/11/2023  999.0
1     02/11/2023  999.0
2     01/11/2023  999.0
3     31/10/2023  999.0
4     30/10/2023  999.0
...          ...    ...
4994  09/01/2004  426.8
4995  08/01/2004  424.4
4996  07/01/2004  422.3
4997  06/01/2004  423.2
4998  05/01/2004  424.8

[4999 rows x 2 columns]

In [4]:
Coin_Price_Of_Historicaldata = pd_Price_Of_Historicaldata.read_csv("/content/drive/MyDrive/Bitcoin_final_data.csv")
Coin_Price_Of_Historicaldata.replace([mu_Price_Of_Historicaldata.inf, -mu_Price_Of_Historicaldata.inf], mu_Price_Of_Historicaldata.nan, inplace=True)
Coin_Price_Of_Historicaldata.fillna(999, inplace=True)
print("Shape details: ",Coin_Price_Of_Historicaldata.shape)
print("Columns details: ",Coin_Price_Of_Historicaldata.columns)
Coin_Price_Of_Historicaldata

Shape details:  (1882, 2)
Columns details:  Index(['Date', 'BTC_Closing'], dtype='object')

            Date   BTC_Closing
0     2018-02-01   9170.540039
1     2018-02-02   8830.750000
2     2018-02-03   9174.910156
3     2018-02-04   8277.009766
4     2018-02-05   6955.270020
...          ...           ...
1877  2023-03-27  27139.888672
1878  2023-03-28  27268.130859
1879  2023-03-29  28348.441406
1880  2023-03-30  28033.562500
1881  2023-03-31  28478.484375

[1882 rows x 2 columns]

In [5]:
import tensorflow as txttflo
from keras.layers import Dense as txttdnse
from keras.layers import GRU as txttgrunt
from sklearn.metrics import r2_score as txtr2scre
from sklearn.metrics import mean_squared_error as txtrmeaser
from sklearn.metrics import mean_absolute_error as txtrmeasqr
from sklearn.model_selection import train_test_split as txtrtsplt
from sklearn.preprocessing import MinMaxScaler as txtrtmnmxsler
from tensorflow.keras.layers import Bidirectional as price_of_histbidirct

In [6]:
def His_SEGFn(txtIpXts_se_His, txtIpXts_n_His):
    vax_txtIpXts, vay_txtIpXts = [], []

    for RRr in range(len(txtIpXts_se_His)):
        Ad_txtIp = RRr + txtIpXts_n_His
        if Ad_txtIp > len(txtIpXts_se_His) - 1:
            break
        x_txtIpXts, y_txtIpXts = txtIpXts_se_His[RRr:Ad_txtIp], txtIpXts_se_His[Ad_txtIp]
        vax_txtIpXts.append(x_txtIpXts)
        vay_txtIpXts.append(y_txtIpXts)
    return mu_Price_Of_Historicaldata.array(vax_txtIpXts), mu_Price_Of_Historicaldata.array(vay_txtIpXts)

txtIpXts_n_His = 20

In [7]:
## train data is - Gold data
vax_txtIpXts_Tnn, vay_txtIpXts_Tnn = His_SEGFn(GOld_Price_Of_Historicaldata['Price'].tolist(), txtIpXts_n_His)
## test data is - Bitcoin data
vax_txtIpXts_Tss, vay_txtIpXts_Tss = His_SEGFn(Coin_Price_Of_Historicaldata['BTC_Closing'].tolist(), txtIpXts_n_His)
for total in range(len(vax_txtIpXts_Tss)):
    print(vax_txtIpXts_Tss[total], vay_txtIpXts_Tss[total])

Streaming output truncated to the last 5000 lines.
 9386.78808594 9450.70214844 9538.02441406 9480.25488281 9411.84082031
 9288.01855469 9332.34082031 9303.62988281 9648.71777344 9629.65820312
 9313.61035156 9264.81347656 9162.91796875 9045.390625   9143.58203125] 9190.8544921875
[9870.09472656 9321.78125    9480.84375    9475.27734375 9386.78808594
 9450.70214844 9538.02441406 9480.25488281 9411.84082031 9288.01855469
 9332.34082031 9303.62988281 9648.71777344 9629.65820312 9313.61035156
 9264.81347656 9162.91796875 9045.390625   9143.58203125 9190.85449219] 9137.9931640625
[9321.78125    9480.84375    9475.27734375 9386.78808594 9450.70214844
 9538.02441406 9480.25488281 9411.84082031 9288.01855469 9332.34082031
 9303.62988281 9648.71777344 9629.65820312 9313.61035156 9264.81347656
 9162.91796875 9045.390625   9143.58203125 9190.85449219 9137.99316406] 9228.3251953125
[9480.84375    9475.27734375 9386.78808594 9450.70214844 9538.02441406
 9480.25488281 9411.84082031 9288.01855469 9332.34082031 9303.62988281
 9648.71777344 9629.65820312 9313.61035156 9264.81347656 9162.91796875
 9045.390625   9143.58203125 9190.85449219 9137.99316406 9228.32519531] 9123.41015625
[9475.27734375 9386.78808594 9450.70214844 9538.02441406 9480.25488281
 9411.84082031 9288.01855469 9332.34082031 9303.62988281 9648.71777344
 9629.65820312 9313.61035156 9264.81347656 9162.91796875 9045.390625
 9143.58203125 9190.85449219 9137.99316406 9228.32519531 9123.41015625] 9087.3037109375
[9386.78808594 9450.70214844 9538.02441406 9480.25488281 9411.84082031
 9288.01855469 9332.34082031 9303.62988281 9648.71777344 9629.65820312
 9313.61035156 9264.81347656 9162.91796875 9045.390625   9143.58203125
 9190.85449219 9137.99316406 9228.32519531 9123.41015625 9087.30371094] 9132.48828125
[9450.70214844 9538.02441406 9480.25488281 9411.84082031 9288.01855469
 9332.34082031 9303.62988281 9648.71777344 9629.65820312 9313.61035156
 9264.81347656 9162.91796875 9045.390625   9143.58203125 9190.85449219
 9137.99316406 9228.32519531 9123.41015625 9087.30371094 9132.48828125] 9073.9423828125
[9538.02441406 9480.25488281 9411.84082031 9288.01855469 9332.34082031
 9303.62988281 9648.71777344 9629.65820312 9313.61035156 9264.81347656
 9162.91796875 9045.390625   9143.58203125 9190.85449219 9137.99316406
 9228.32519531 9123.41015625 9087.30371094 9132.48828125 9073.94238281] 9375.474609375
[9480.25488281 9411.84082031 9288.01855469 9332.34082031 9303.62988281
 9648.71777344 9629.65820312 9313.61035156 9264.81347656 9162.91796875
 9045.390625   9143.58203125 9190.85449219 9137.99316406 9228.32519531
 9123.41015625 9087.30371094 9132.48828125 9073.94238281 9375.47460938] 9252.27734375
[9411.84082031 9288.01855469 9332.34082031 9303.62988281 9648.71777344
 9629.65820312 9313.61035156 9264.81347656 9162.91796875 9045.390625
 9143.58203125 9190.85449219 9137.99316406 9228.32519531 9123.41015625
 9087.30371094 9132.48828125 9073.94238281 9375.47460938 9252.27734375] 9428.3330078125
[9288.01855469 9332.34082031 9303.62988281 9648.71777344 9629.65820312
 9313.61035156 9264.81347656 9162.91796875 9045.390625   9143.58203125
 9190.85449219 9137.99316406 9228.32519531 9123.41015625 9087.30371094
 9132.48828125 9073.94238281 9375.47460938 9252.27734375 9428.33300781] 9277.9677734375
[9332.34082031 9303.62988281 9648.71777344 9629.65820312 9313.61035156
 9264.81347656 9162.91796875 9045.390625   9143.58203125 9190.85449219
 9137.99316406 9228.32519531 9123.41015625 9087.30371094 9132.48828125
 9073.94238281 9375.47460938 9252.27734375 9428.33300781 9277.96777344] 9278.8076171875
[9303.62988281 9648.71777344 9629.65820312 9313.61035156 9264.81347656
 9162.91796875 9045.390625   9143.58203125 9190.85449219 9137.99316406
 9228.32519531 9123.41015625 9087.30371094 9132.48828125 9073.94238281
 9375.47460938 9252.27734375 9428.33300781 9277.96777344 9278.80761719] 9240.3466796875
[9648.71777344 9629.65820312 9313.61035156 9264.81347656 9162.91796875
 9045.390625   9143.58203125 9190.85449219 9137.99316406 9228.32519531
 9123.41015625 9087.30371094 9132.48828125 9073.94238281 9375.47460938
 9252.27734375 9428.33300781 9277.96777344 9278.80761719 9240.34667969] 9276.5
[9629.65820312 9313.61035156 9264.81347656 9162.91796875 9045.390625
 9143.58203125 9190.85449219 9137.99316406 9228.32519531 9123.41015625
 9087.30371094 9132.48828125 9073.94238281 9375.47460938 9252.27734375
 9428.33300781 9277.96777344 9278.80761719 9240.34667969 9276.5       ] 9243.6142578125
[9313.61035156 9264.81347656 9162.91796875 9045.390625   9143.58203125
 9190.85449219 9137.99316406 9228.32519531 9123.41015625 9087.30371094
 9132.48828125 9073.94238281 9375.47460938 9252.27734375 9428.33300781
 9277.96777344 9278.80761719 9240.34667969 9276.5        9243.61425781] 9243.2138671875
[9264.81347656 9162.91796875 9045.390625   9143.58203125 9190.85449219
 9137.99316406 9228.32519531 9123.41015625 9087.30371094 9132.48828125
 9073.94238281 9375.47460938 9252.27734375 9428.33300781 9277.96777344
 9278.80761719 9240.34667969 9276.5        9243.61425781 9243.21386719] 9192.8369140625
[9162.91796875 9045.390625   9143.58203125 9190.85449219 9137.99316406
 9228.32519531 9123.41015625 9087.30371094 9132.48828125 9073.94238281
 9375.47460938 9252.27734375 9428.33300781 9277.96777344 9278.80761719
 9240.34667969 9276.5        9243.61425781 9243.21386719 9192.83691406] 9132.2275390625
[9045.390625   9143.58203125 9190.85449219 9137.99316406 9228.32519531
 9123.41015625 9087.30371094 9132.48828125 9073.94238281 9375.47460938
 9252.27734375 9428.33300781 9277.96777344 9278.80761719 9240.34667969
 9276.5        9243.61425781 9243.21386719 9192.83691406 9132.22753906] 9151.392578125
[9143.58203125 9190.85449219 9137.99316406 9228.32519531 9123.41015625
 9087.30371094 9132.48828125 9073.94238281 9375.47460938 9252.27734375
 9428.33300781 9277.96777344 9278.80761719 9240.34667969 9276.5
 9243.61425781 9243.21386719 9192.83691406 9132.22753906 9151.39257812] 9159.0400390625
[9190.85449219 9137.99316406 9228.32519531 9123.41015625 9087.30371094
 9132.48828125 9073.94238281 9375.47460938 9252.27734375 9428.33300781
 9277.96777344 9278.80761719 9240.34667969 9276.5        9243.61425781
 9243.21386719 9192.83691406 9132.22753906 9151.39257812 9159.04003906] 9185.8173828125
[9137.99316406 9228.32519531 9123.41015625 9087.30371094 9132.48828125
 9073.94238281 9375.47460938 9252.27734375 9428.33300781 9277.96777344
 9278.80761719 9240.34667969 9276.5        9243.61425781 9243.21386719
 9192.83691406 9132.22753906 9151.39257812 9159.04003906 9185.81738281] 9164.2314453125
[9228.32519531 9123.41015625 9087.30371094 9132.48828125 9073.94238281
 9375.47460938 9252.27734375 9428.33300781 9277.96777344 9278.80761719
 9240.34667969 9276.5        9243.61425781 9243.21386719 9192.83691406
 9132.22753906 9151.39257812 9159.04003906 9185.81738281 9164.23144531] 9374.8876953125
[9123.41015625 9087.30371094 9132.48828125 9073.94238281 9375.47460938
 9252.27734375 9428.33300781 9277.96777344 9278.80761719 9240.34667969
 9276.5        9243.61425781 9243.21386719 9192.83691406 9132.22753906
 9151.39257812 9159.04003906 9185.81738281 9164.23144531 9374.88769531] 9525.36328125
[9087.30371094 9132.48828125 9073.94238281 9375.47460938 9252.27734375
 9428.33300781 9277.96777344 9278.80761719 9240.34667969 9276.5
 9243.61425781 9243.21386719 9192.83691406 9132.22753906 9151.39257812
 9159.04003906 9185.81738281 9164.23144531 9374.88769531 9525.36328125] 9581.072265625
[9132.48828125 9073.94238281 9375.47460938 9252.27734375 9428.33300781
 9277.96777344 9278.80761719 9240.34667969 9276.5        9243.61425781
 9243.21386719 9192.83691406 9132.22753906 9151.39257812 9159.04003906
 9185.81738281 9164.23144531 9374.88769531 9525.36328125 9581.07226562] 9536.892578125
[9073.94238281 9375.47460938 9252.27734375 9428.33300781 9277.96777344
 9278.80761719 9240.34667969 9276.5        9243.61425781 9243.21386719
 9192.83691406 9132.22753906 9151.39257812 9159.04003906 9185.81738281
 9164.23144531 9374.88769531 9525.36328125 9581.07226562 9536.89257812] 9677.11328125
[9375.47460938 9252.27734375 9428.33300781 9277.96777344 9278.80761719
 9240.34667969 9276.5        9243.61425781 9243.21386719 9192.83691406
 9132.22753906 9151.39257812 9159.04003906 9185.81738281 9164.23144531
 9374.88769531 9525.36328125 9581.07226562 9536.89257812 9677.11328125] 9905.1669921875
[9252.27734375 9428.33300781 9277.96777344 9278.80761719 9240.34667969
 9276.5        9243.61425781 9243.21386719 9192.83691406 9132.22753906
 9151.39257812 9159.04003906 9185.81738281 9164.23144531 9374.88769531
 9525.36328125 9581.07226562 9536.89257812 9677.11328125 9905.16699219] 10990.873046875
[ 9428.33300781  9277.96777344  9278.80761719  9240.34667969
  9276.5         9243.61425781  9243.21386719  9192.83691406
  9132.22753906  9151.39257812  9159.04003906  9185.81738281
  9164.23144531  9374.88769531  9525.36328125  9581.07226562
  9536.89257812  9677.11328125  9905.16699219 10990.87304688] 10912.8232421875
[ 9277.96777344  9278.80761719  9240.34667969  9276.5
  9243.61425781  9243.21386719  9192.83691406  9132.22753906
  9151.39257812  9159.04003906  9185.81738281  9164.23144531
  9374.88769531  9525.36328125  9581.07226562  9536.89257812
  9677.11328125  9905.16699219 10990.87304688 10912.82324219] 11100.4677734375
[ 9278.80761719  9240.34667969  9276.5         9243.61425781
  9243.21386719  9192.83691406  9132.22753906  9151.39257812
  9159.04003906  9185.81738281  9164.23144531  9374.88769531
  9525.36328125  9581.07226562  9536.89257812  9677.11328125
  9905.16699219 10990.87304688 10912.82324219 11100.46777344] 11111.2138671875
[ 9240.34667969  9276.5         9243.61425781  9243.21386719
  9192.83691406  9132.22753906  9151.39257812  9159.04003906
  9185.81738281  9164.23144531  9374.88769531  9525.36328125
  9581.07226562  9536.89257812  9677.11328125  9905.16699219
 10990.87304688 10912.82324219 11100.46777344 11111.21386719] 11323.466796875
[ 9276.5         9243.61425781  9243.21386719  9192.83691406
  9132.22753906  9151.39257812  9159.04003906  9185.81738281
  9164.23144531  9374.88769531  9525.36328125  9581.07226562
  9536.89257812  9677.11328125  9905.16699219 10990.87304688
 10912.82324219 11100.46777344 11111.21386719 11323.46679688] 11759.5927734375
[ 9243.61425781  9243.21386719  9192.83691406  9132.22753906
  9151.39257812  9159.04003906  9185.81738281  9164.23144531
  9374.88769531  9525.36328125  9581.07226562  9536.89257812
  9677.11328125  9905.16699219 10990.87304688 10912.82324219
 11100.46777344 11111.21386719 11323.46679688 11759.59277344] 11053.6142578125
[ 9243.21386719  9192.83691406  9132.22753906  9151.39257812
  9159.04003906  9185.81738281  9164.23144531  9374.88769531
  9525.36328125  9581.07226562  9536.89257812  9677.11328125
  9905.16699219 10990.87304688 10912.82324219 11100.46777344
 11111.21386719 11323.46679688 11759.59277344 11053.61425781] 11246.3486328125
[ 9192.83691406  9132.22753906  9151.39257812  9159.04003906
  9185.81738281  9164.23144531  9374.88769531  9525.36328125
  9581.07226562  9536.89257812  9677.11328125  9905.16699219
 10990.87304688 10912.82324219 11100.46777344 11111.21386719
 11323.46679688 11759.59277344 11053.61425781 11246.34863281] 11205.892578125
[ 9132.22753906  9151.39257812  9159.04003906  9185.81738281
  9164.23144531  9374.88769531  9525.36328125  9581.07226562
  9536.89257812  9677.11328125  9905.16699219 10990.87304688
 10912.82324219 11100.46777344 11111.21386719 11323.46679688
 11759.59277344 11053.61425781 11246.34863281 11205.89257812] 11747.0224609375
[ 9151.39257812  9159.04003906  9185.81738281  9164.23144531
  9374.88769531  9525.36328125  9581.07226562  9536.89257812
  9677.11328125  9905.16699219 10990.87304688 10912.82324219
 11100.46777344 11111.21386719 11323.46679688 11759.59277344
 11053.61425781 11246.34863281 11205.89257812 11747.02246094] 11779.7734375
[ 9159.04003906  9185.81738281  9164.23144531  9374.88769531
  9525.36328125  9581.07226562  9536.89257812  9677.11328125
  9905.16699219 10990.87304688 10912.82324219 11100.46777344
 11111.21386719 11323.46679688 11759.59277344 11053.61425781
 11246.34863281 11205.89257812 11747.02246094 11779.7734375 ] 11601.47265625
[ 9185.81738281  9164.23144531  9374.88769531  9525.36328125
  9581.07226562  9536.89257812  9677.11328125  9905.16699219
 10990.87304688 10912.82324219 11100.46777344 11111.21386719
 11323.46679688 11759.59277344 11053.61425781 11246.34863281
 11205.89257812 11747.02246094 11779.7734375  11601.47265625] 11754.0458984375
[ 9164.23144531  9374.88769531  9525.36328125  9581.07226562
  9536.89257812  9677.11328125  9905.16699219 10990.87304688
 10912.82324219 11100.46777344 11111.21386719 11323.46679688
 11759.59277344 11053.61425781 11246.34863281 11205.89257812
 11747.02246094 11779.7734375  11601.47265625 11754.04589844] 11675.7392578125
[ 9374.88769531  9525.36328125  9581.07226562  9536.89257812
  9677.11328125  9905.16699219 10990.87304688 10912.82324219
 11100.46777344 11111.21386719 11323.46679688 11759.59277344
 11053.61425781 11246.34863281 11205.89257812 11747.02246094
 11779.7734375  11601.47265625 11754.04589844 11675.73925781] 11878.111328125
[ 9525.36328125  9581.07226562  9536.89257812  9677.11328125
  9905.16699219 10990.87304688 10912.82324219 11100.46777344
 11111.21386719 11323.46679688 11759.59277344 11053.61425781
 11246.34863281 11205.89257812 11747.02246094 11779.7734375
 11601.47265625 11754.04589844 11675.73925781 11878.11132812] 11410.525390625
[ 9581.07226562  9536.89257812  9677.11328125  9905.16699219
 10990.87304688 10912.82324219 11100.46777344 11111.21386719
 11323.46679688 11759.59277344 11053.61425781 11246.34863281
 11205.89257812 11747.02246094 11779.7734375  11601.47265625
 11754.04589844 11675.73925781 11878.11132812 11410.52539062] 11584.9345703125
[ 9536.89257812  9677.11328125  9905.16699219 10990.87304688
 10912.82324219 11100.46777344 11111.21386719 11323.46679688
 11759.59277344 11053.61425781 11246.34863281 11205.89257812
 11747.02246094 11779.7734375  11601.47265625 11754.04589844
 11675.73925781 11878.11132812 11410.52539062 11584.93457031] 11784.1376953125
[ 9677.11328125  9905.16699219 10990.87304688 10912.82324219
 11100.46777344 11111.21386719 11323.46679688 11759.59277344
 11053.61425781 11246.34863281 11205.89257812 11747.02246094
 11779.7734375  11601.47265625 11754.04589844 11675.73925781
 11878.11132812 11410.52539062 11584.93457031 11784.13769531] 11768.87109375
[ 9905.16699219 10990.87304688 10912.82324219 11100.46777344
 11111.21386719 11323.46679688 11759.59277344 11053.61425781
 11246.34863281 11205.89257812 11747.02246094 11779.7734375
 11601.47265625 11754.04589844 11675.73925781 11878.11132812
 11410.52539062 11584.93457031 11784.13769531 11768.87109375] 11865.6982421875
[10990.87304688 10912.82324219 11100.46777344 11111.21386719
 11323.46679688 11759.59277344 11053.61425781 11246.34863281
 11205.89257812 11747.02246094 11779.7734375  11601.47265625
 11754.04589844 11675.73925781 11878.11132812 11410.52539062
 11584.93457031 11784.13769531 11768.87109375 11865.69824219] 11892.8037109375
[10912.82324219 11100.46777344 11111.21386719 11323.46679688
 11759.59277344 11053.61425781 11246.34863281 11205.89257812
 11747.02246094 11779.7734375  11601.47265625 11754.04589844
 11675.73925781 11878.11132812 11410.52539062 11584.93457031
 11784.13769531 11768.87109375 11865.69824219 11892.80371094] 12254.40234375
[11100.46777344 11111.21386719 11323.46679688 11759.59277344
 11053.61425781 11246.34863281 11205.89257812 11747.02246094
 11779.7734375  11601.47265625 11754.04589844 11675.73925781
 11878.11132812 11410.52539062 11584.93457031 11784.13769531
 11768.87109375 11865.69824219 11892.80371094 12254.40234375] 11991.2333984375
[11111.21386719 11323.46679688 11759.59277344 11053.61425781
 11246.34863281 11205.89257812 11747.02246094 11779.7734375
 11601.47265625 11754.04589844 11675.73925781 11878.11132812
 11410.52539062 11584.93457031 11784.13769531 11768.87109375
 11865.69824219 11892.80371094 12254.40234375 11991.23339844] 11758.283203125
[11323.46679688 11759.59277344 11053.61425781 11246.34863281
 11205.89257812 11747.02246094 11779.7734375  11601.47265625
 11754.04589844 11675.73925781 11878.11132812 11410.52539062
 11584.93457031 11784.13769531 11768.87109375 11865.69824219
 11892.80371094 12254.40234375 11991.23339844 11758.28320312] 11878.3720703125
[11759.59277344 11053.61425781 11246.34863281 11205.89257812
 11747.02246094 11779.7734375  11601.47265625 11754.04589844
 11675.73925781 11878.11132812 11410.52539062 11584.93457031
 11784.13769531 11768.87109375 11865.69824219 11892.80371094
 12254.40234375 11991.23339844 11758.28320312 11878.37207031] 11592.4892578125
[11053.61425781 11246.34863281 11205.89257812 11747.02246094
 11779.7734375  11601.47265625 11754.04589844 11675.73925781
 11878.11132812 11410.52539062 11584.93457031 11784.13769531
 11768.87109375 11865.69824219 11892.80371094 12254.40234375
 11991.23339844 11758.28320312 11878.37207031 11592.48925781] 11681.8251953125
[11246.34863281 11205.89257812 11747.02246094 11779.7734375
 11601.47265625 11754.04589844 11675.73925781 11878.11132812
 11410.52539062 11584.93457031 11784.13769531 11768.87109375
 11865.69824219 11892.80371094 12254.40234375 11991.23339844
 11758.28320312 11878.37207031 11592.48925781 11681.82519531] 11664.84765625
[11205.89257812 11747.02246094 11779.7734375  11601.47265625
 11754.04589844 11675.73925781 11878.11132812 11410.52539062
 11584.93457031 11784.13769531 11768.87109375 11865.69824219
 11892.80371094 12254.40234375 11991.23339844 11758.28320312
 11878.37207031 11592.48925781 11681.82519531 11664.84765625] 11774.595703125
[11747.02246094 11779.7734375  11601.47265625 11754.04589844
 11675.73925781 11878.11132812 11410.52539062 11584.93457031
 11784.13769531 11768.87109375 11865.69824219 11892.80371094
 12254.40234375 11991.23339844 11758.28320312 11878.37207031
 11592.48925781 11681.82519531 11664.84765625 11774.59570312] 11366.134765625
[11779.7734375  11601.47265625 11754.04589844 11675.73925781
 11878.11132812 11410.52539062 11584.93457031 11784.13769531
 11768.87109375 11865.69824219 11892.80371094 12254.40234375
 11991.23339844 11758.28320312 11878.37207031 11592.48925781
 11681.82519531 11664.84765625 11774.59570312 11366.13476562] 11488.36328125
[11601.47265625 11754.04589844 11675.73925781 11878.11132812
 11410.52539062 11584.93457031 11784.13769531 11768.87109375
 11865.69824219 11892.80371094 12254.40234375 11991.23339844
 11758.28320312 11878.37207031 11592.48925781 11681.82519531
 11664.84765625 11774.59570312 11366.13476562 11488.36328125] 11323.3974609375
[11754.04589844 11675.73925781 11878.11132812 11410.52539062
 11584.93457031 11784.13769531 11768.87109375 11865.69824219
 11892.80371094 12254.40234375 11991.23339844 11758.28320312
 11878.37207031 11592.48925781 11681.82519531 11664.84765625
 11774.59570312 11366.13476562 11488.36328125 11323.39746094] 11542.5
[11675.73925781 11878.11132812 11410.52539062 11584.93457031
 11784.13769531 11768.87109375 11865.69824219 11892.80371094
 12254.40234375 11991.23339844 11758.28320312 11878.37207031
 11592.48925781 11681.82519531 11664.84765625 11774.59570312
 11366.13476562 11488.36328125 11323.39746094 11542.5       ] 11506.865234375
[11878.11132812 11410.52539062 11584.93457031 11784.13769531
 11768.87109375 11865.69824219 11892.80371094 12254.40234375
 11991.23339844 11758.28320312 11878.37207031 11592.48925781
 11681.82519531 11664.84765625 11774.59570312 11366.13476562
 11488.36328125 11323.39746094 11542.5        11506.86523438] 11711.505859375
[11410.52539062 11584.93457031 11784.13769531 11768.87109375
 11865.69824219 11892.80371094 12254.40234375 11991.23339844
 11758.28320312 11878.37207031 11592.48925781 11681.82519531
 11664.84765625 11774.59570312 11366.13476562 11488.36328125
 11323.39746094 11542.5        11506.86523438 11711.50585938] 11680.8203125
[11584.93457031 11784.13769531 11768.87109375 11865.69824219

In [8]:
srtxtrtmnmxsler = txtrtmnmxsler()
vax_txtIpXts_Tnn_sca = srtxtrtmnmxsler.fit_transform(vax_txtIpXts_Tnn)
vax_txtIpXts_Tss_sca = srtxtrtmnmxsler.transform(vax_txtIpXts_Tss)

txtIpXtrrshped = vax_txtIpXts_Tnn_sca.reshape((vax_txtIpXts_Tnn_sca.shape[0], 1, vax_txtIpXts_Tnn_sca.shape[1]))
txtIpXtsrshped = vax_txtIpXts_Tss_sca.reshape((vax_txtIpXts_Tss_sca.shape[0], 1, vax_txtIpXts_Tss_sca.shape[1]))

 changing both Optimizer and activation function

GRU

In [9]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(txttgrunt(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2])))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse', metrics=['accuracy'])

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
Optimizer is: adam, activation is: relu
R-squared: 0.49710692422588165
Mean Squared Error: 141245184.43697855
Mean Absolute Error: 8702.64978617372
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: adam, activation is: tanh
R-squared: -1.5170546480173415
Mean Squared Error: 706953157.8852983
Mean Absolute Error: 20641.89714766522
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -1.5179726471230133
Mean Squared Error: 707210991.9244606
Mean Absolute Error: 20648.14160872479
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: sgd, activation is: relu
R-squared: -1.3991873309799225
Mean Squared Error: 673848325.5938315
Mean Absolute Error: 19823.800986776547
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -1.3378466101408786
Mean Squared Error: 656619849.3117291
Mean Absolute Error: 19384.82788407175
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -1.3639923924431105
Mean Squared Error: 663963290.7338308
Mean Absolute Error: 19581.51868078967
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: 0.6002620308800855
Mean Squared Error: 112272500.6461729
Mean Absolute Error: 7695.203648158482
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -1.5175308485131072
Mean Squared Error: 707086906.0518441
Mean Absolute Error: 20645.136619100766
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -1.5185871745519814
Mean Squared Error: 707383591.318303
Mean Absolute Error: 20652.3207240202
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1.4932805029947085
Mean Squared Error: 700275826.9369963
Mean Absolute Error: 20574.976365779832
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1.5287226054538636
Mean Squared Error: 710230281.5513729
Mean Absolute Error: 20721.19193362832
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1.5287020209467719
Mean Squared Error: 710224500.0788476
Mean Absolute Error: 20721.0561206958
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1.4352428495009466
Mean Squared Error: 683975067.4576634
Mean Absolute Error: 20334.940305810225
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1.5273748907105555
Mean Squared Error: 709851755.326501
Mean Absolute Error: 20711.99532051322
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1.5282590935099223
Mean Squared Error: 710100097.1579808
Mean Absolute Error: 20717.983730470198
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
Optimizer is: adamax, activation is: relu
R-squared: 0.48921455627717736
Mean Squared Error: 143461876.2553005
Mean Absolute Error: 8777.358686109106
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -1.5185183633758395
Mean Squared Error: 707364264.6507992
Mean Absolute Error: 20651.852813253598
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -1.5220281282024666
Mean Squared Error: 708350035.5912805
Mean Absolute Error: 20675.729607619993
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: nadam, activation is: relu
R-squared: 0.4632362609375591
Mean Squared Error: 150758276.41144583
Mean Absolute Error: 9016.695122904219
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -1.5170638919685913
Mean Squared Error: 706955754.1898849
Mean Absolute Error: 20641.96003676434
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -1.5179396830276577
Mean Squared Error: 707201733.4559062
Mean Absolute Error: 20647.917411337094
---

BiDirectional GRU

In [10]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(price_of_histbidirct(txttgrunt(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2]))))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse')

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adam, activation is: relu
R-squared: 0.4740994249941257
Mean Squared Error: 147707191.23120743
Mean Absolute Error: 8916.056674715528
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adam, activation is: tanh
R-squared: -1.5067795294962618
Mean Squared Error: 704067234.2555333
Mean Absolute Error: 20571.87386275311
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -1.5073163634276114
Mean Squared Error: 704218012.2465183
Mean Absolute Error: 20575.538199911312
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: sgd, activation is: relu
R-squared: -1.3990059304423097
Mean Squared Error: 673797376.4882932
Mean Absolute Error: 19822.515909164216
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -1.3243697244503054
Mean Squared Error: 652834660.5773824
Mean Absolute Error: 19291.382431276117
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -1.3228839735229672
Mean Squared Error: 652417364.78655
Mean Absolute Error: 19275.687400350766
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: 0.6836672631718881
Mean Squared Error: 88846870.0587354
Mean Absolute Error: 6774.788924826716
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -1.50728298987057
Mean Squared Error: 704208638.7744092
Mean Absolute Error: 20575.310416708187
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -1.5084143555240006
Mean Squared Error: 704526400.0602223
Mean Absolute Error: 20583.030875692562
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adadelta, activation is: relu
R-squared: 0.8500648403379701
Mean Squared Error: 42111574.60748867
Mean Absolute Error: 4791.676610829879
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1.5285680801170374
Mean Squared Error: 710186880.7555543
Mean Absolute Error: 20720.139478613048
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1.5288116987985827
Mean Squared Error: 710255304.7750225
Mean Absolute Error: 20721.697765376644
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1.4085104926510872
Mean Squared Error: 676466877.6344465
Mean Absolute Error: 20222.832050897126
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1.5263670773593736
Mean Squared Error: 709568695.5877153
Mean Absolute Error: 20705.157158984788
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1.527611324600116
Mean Squared Error: 709918161.3876437
Mean Absolute Error: 20713.592456342325
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step
Optimizer is: adamax, activation is: relu
R-squared: 0.474742277933883
Mean Squared Error: 147526636.18597817
Mean Absolute Error: 8912.288576578863
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -1.508840679776474
Mean Squared Error: 704646139.7237241
Mean Absolute Error: 20585.939368734555
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -1.5129800095237838
Mean Squared Error: 705808733.5667676
Mean Absolute Error: 20614.15759739123
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: nadam, activation is: relu
R-squared: 0.49255011531286585
Mean Squared Error: 142525033.66610593
Mean Absolute Error: 8751.062728406536
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -1.5065278151998887
Mean Squared Error: 703996536.4592634
Mean Absolute Error: 20570.155478964047
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -1.5078143703825901
Mean Squared Error: 704357885.0894654
Mean Absolute Error: 20578.936927328305
---

LSTM

In [11]:
from keras.layers import LSTM as txttlngtm

In [12]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(txttlngtm(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2])))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse', metrics=['accuracy'])

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adam, activation is: relu
R-squared: 0.2799365557947844
Mean Squared Error: 202240792.09389272
Mean Absolute Error: 10529.937266348768
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adam, activation is: tanh
R-squared: -1.519703594185402
Mean Squared Error: 707697154.7866185
Mean Absolute Error: 20659.910811910824
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -1.5206924561659827
Mean Squared Error: 707974891.7441514
Mean Absolute Error: 20666.631358633236
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: sgd, activation is: relu
R-squared: -1.399006010107291
Mean Squared Error: 673797398.8634174
Mean Absolute Error: 19822.51651990913
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -1.3930062740819773
Mean Squared Error: 672112281.5645479
Mean Absolute Error: 19765.974153086398
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -1.3586653189157047
Mean Squared Error: 662467100.9488958
Mean Absolute Error: 19534.632346639828
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: 0.27343535003327324
Mean Squared Error: 204066754.81058726
Mean Absolute Error: 10580.054850610062
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -1.5202209877703283
Mean Squared Error: 707842472.6600391
Mean Absolute Error: 20663.42741728802
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -1.5210875871579237
Mean Squared Error: 708085870.3050463
Mean Absolute Error: 20669.316154012875
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1.5222629495316449
Mean Squared Error: 708415988.7402644
Mean Absolute Error: 20696.431958338435
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1.52863653866306
Mean Squared Error: 710206108.3815151
Mean Absolute Error: 20720.545939522068
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1.5286090658128586
Mean Squared Error: 710198392.2128489
Mean Absolute Error: 20720.419719781257
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1.4248683338421029
Mean Squared Error: 681061226.626942
Mean Absolute Error: 20291.707367902156
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1.5277169404109165
Mean Squared Error: 709947825.1976951
Mean Absolute Error: 20714.265891464132
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1.5282817697004467
Mean Squared Error: 710106466.1116754
Mean Absolute Error: 20718.137981856293
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adamax, activation is: relu
R-squared: 0.4698516356493969
Mean Squared Error: 148900247.60511371
Mean Absolute Error: 8931.081317709033
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -1.5207780917917453
Mean Squared Error: 707998943.8147364
Mean Absolute Error: 20667.213256368832
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -1.522911513341357
Mean Squared Error: 708598147.7703543
Mean Absolute Error: 20681.70824197591
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: nadam, activation is: relu
R-squared: 0.31671831915604154
Mean Squared Error: 191910073.29868788
Mean Absolute Error: 10240.28266056114
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -1.519634759403241
Mean Squared Error: 707677821.4890044
Mean Absolute Error: 20659.442912588314
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -1.5208780218955216
Mean Squared Error: 708027010.7073197
Mean Absolute Error: 20667.892265565668
---

Bidirectional LSTM

In [13]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(price_of_histbidirct(txttlngtm(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2]))))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse')

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adam, activation is: relu
R-squared: 0.2970165608871359
Mean Squared Error: 197443612.3639071
Mean Absolute Error: 10400.525749362245
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adam, activation is: tanh
R-squared: -1.5114671318276267
Mean Squared Error: 705383818.8094996
Mean Absolute Error: 20603.84863997479
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -1.5127883500176682
Mean Squared Error: 705754903.0735784
Mean Absolute Error: 20612.85189009686
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: sgd, activation is: relu
R-squared: -1.3996333410300879
Mean Squared Error: 673973594.3136272
Mean Absolute Error: 19826.96028853436
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -1.3590334232092451
Mean Squared Error: 662570488.6496572
Mean Absolute Error: 19532.674495184845
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -1.361197660898391
Mean Squared Error: 663178347.7877023
Mean Absolute Error: 19552.82865530438
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: 0.46704183975730706
Mean Squared Error: 149689421.60278228
Mean Absolute Error: 8980.783371217525
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -1.5123257257598453
Mean Squared Error: 705624968.000361
Mean Absolute Error: 20609.69985152264
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -1.513861118656168
Mean Squared Error: 706056206.4947277
Mean Absolute Error: 20620.15922499676
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1.523687362853328
Mean Squared Error: 708816056.9297615
Mean Absolute Error: 20700.22063005086
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1.528698870189682
Mean Squared Error: 710223615.1407013
Mean Absolute Error: 20720.992981034753
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1.5287892153158058
Mean Squared Error: 710248989.9462355
Mean Absolute Error: 20721.527984228636
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1.3666252703051232
Mean Squared Error: 664702774.606516
Mean Absolute Error: 20046.95226630386
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1.5269995662279476
Mean Squared Error: 709746339.7256039
Mean Absolute Error: 20709.450145189283
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1.528015617207409
Mean Squared Error: 710031713.1278336
Mean Absolute Error: 20716.334516863306
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adamax, activation is: relu
R-squared: 0.2916939730853384
Mean Squared Error: 198938542.2644424
Mean Absolute Error: 10438.545438739846
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -1.513492657978499
Mean Squared Error: 705952718.6980524
Mean Absolute Error: 20617.649688253598
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -1.5165105369497085
Mean Squared Error: 706800335.9996842
Mean Absolute Error: 20638.19507468579
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
Optimizer is: nadam, activation is: relu
R-squared: 0.2889591377562224
Mean Squared Error: 199706662.4455985
Mean Absolute Error: 10460.199636227846
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -1.511440755304633
Mean Squared Error: 705376410.5610379
Mean Absolute Error: 20603.668860922055
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -1.5127288898849245
Mean Squared Error: 705738202.789123
Mean Absolute Error: 20612.446792135433
---

RNN

In [14]:
from keras.layers import SimpleRNN as txttsmprn

In [15]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(txttsmprn(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2])))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse', metrics=['accuracy'])

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: adam, activation is: relu
R-squared: 0.31915266847082446
Mean Squared Error: 191226349.19407323
Mean Absolute Error: 10219.557448046036
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: adam, activation is: tanh
R-squared: -1.5174927534471556
Mean Squared Error: 707076206.4720017
Mean Absolute Error: 20644.87748671551
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -1.5187280464937847
Mean Squared Error: 707423157.3500513
Mean Absolute Error: 20653.28548211365
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: sgd, activation is: relu
R-squared: -1.3992373152064772
Mean Squared Error: 673862364.4256206
Mean Absolute Error: 19824.155146384725
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -1.2978460948602568
Mean Squared Error: 645385094.9860932
Mean Absolute Error: 19076.569525926632
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -1.343876837613454
Mean Squared Error: 658313530.5982524
Mean Absolute Error: 19455.423184731848
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: 0.2856913267783495
Mean Squared Error: 200624476.9602731
Mean Absolute Error: 10484.819124838463
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -1.5177572304401696
Mean Squared Error: 707150488.8661271
Mean Absolute Error: 20646.676459799008
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -1.5184363989915277
Mean Squared Error: 707341243.7043256
Mean Absolute Error: 20651.295447836117
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1.5302597027588645
Mean Squared Error: 710661998.7548921
Mean Absolute Error: 20727.66672978338
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1.5288106694513592
Mean Squared Error: 710255015.6671675
Mean Absolute Error: 20721.821217243094
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1.5284921674653358
Mean Squared Error: 710165559.5304128
Mean Absolute Error: 20719.543790442025
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1.4365416515718414
Mean Squared Error: 684339855.8130574
Mean Absolute Error: 20340.309015661252
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1.5274320149787095
Mean Squared Error: 709867799.5477875
Mean Absolute Error: 20712.377000006647
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1.5279778979718048
Mean Squared Error: 710021119.1056719
Mean Absolute Error: 20716.072809512327
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adamax, activation is: relu
R-squared: 0.310451865636969
Mean Squared Error: 193670102.2704622
Mean Absolute Error: 10291.672652264031
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -1.5183165647715016
Mean Squared Error: 707307586.437354
Mean Absolute Error: 20650.480536947445
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -1.5218487292653466
Mean Squared Error: 708299648.665745
Mean Absolute Error: 20674.485398355027
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: nadam, activation is: relu
R-squared: 0.28277299289895297
Mean Squared Error: 201444135.50579897
Mean Absolute Error: 10506.647555342039
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -1.517261666340453
Mean Squared Error: 707011302.1363096
Mean Absolute Error: 20643.30550337811
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -1.5179092768667943
Mean Squared Error: 707193193.4222369
Mean Absolute Error: 20647.71060896893
---

Bidirectional RNN

In [17]:
txtoptmzers = ['adam', 'sgd', 'rmsprop', 'adadelta', 'adagrad', 'adamax', 'nadam']
txtoactvtns = ['relu', 'tanh', 'sigmoid']

for txtoptmzer in txtoptmzers:
  for txtoactvtn in txtoactvtns:
    txtmdle = txttflo.keras.models.Sequential()
    txtmdle.add(price_of_histbidirct(txttsmprn(32, activation=txtoactvtn, input_shape=(txtIpXtrrshped.shape[1], txtIpXtrrshped.shape[2]))))
    txtmdle.add(txttdnse(1))
    txtmdle.compile(optimizer=txtoptmzer, loss='mse')

    txtmdle.fit(txtIpXtrrshped, vay_txtIpXts_Tnn, epochs=30, batch_size=72, verbose=0)
    txtprdtns = txtmdle.predict(txtIpXtsrshped)
    txtr2sr = txtr2scre(vay_txtIpXts_Tss, txtprdtns)
    txtmsae = txtrmeaser(vay_txtIpXts_Tss, txtprdtns)
    txtmase = txtrmeasqr(vay_txtIpXts_Tss, txtprdtns)

    print(f'Optimizer is: {txtoptmzer}, activation is: {txtoactvtn}')
    print('R-squared:', txtr2sr)
    print('Mean Squared Error:', txtmsae)
    print('Mean Absolute Error:', txtmase)
    print('---')

59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adam, activation is: relu
R-squared: 0.28320959665846157
Mean Squared Error: 201321508.68608636
Mean Absolute Error: 10506.56968785664
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: adam, activation is: tanh
R-squared: -1.507499381300255
Mean Squared Error: 704269415.6052482
Mean Absolute Error: 20576.787299642758
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adam, activation is: sigmoid
R-squared: -1.5074383405721625
Mean Squared Error: 704252271.386501
Mean Absolute Error: 20576.370704183773
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: sgd, activation is: relu
R-squared: -1.3992080349851554
Mean Squared Error: 673854140.6292309
Mean Absolute Error: 19823.947654257016
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: sgd, activation is: tanh
R-squared: -1.3162961669882574
Mean Squared Error: 650567078.9229043
Mean Absolute Error: 19216.423885161075
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: sgd, activation is: sigmoid
R-squared: -1.3632911420907736
Mean Squared Error: 663766333.8853002
Mean Absolute Error: 19569.42296353677
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: rmsprop, activation is: relu
R-squared: 0.4251965104091747
Mean Squared Error: 161442320.07430115
Mean Absolute Error: 9349.595943332102
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: rmsprop, activation is: tanh
R-squared: -1.507500177239089
Mean Squared Error: 704269639.1567999
Mean Absolute Error: 20576.792731771664
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: rmsprop, activation is: sigmoid
R-squared: -1.508581439468414
Mean Squared Error: 704573328.1323752
Mean Absolute Error: 20584.170814047055
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adadelta, activation is: relu
R-squared: -1.5354401977617123
Mean Squared Error: 712117019.7273438
Mean Absolute Error: 20748.68987073742
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: adadelta, activation is: tanh
R-squared: -1.5285774509853431
Mean Squared Error: 710189512.7067304
Mean Absolute Error: 20720.162268115324
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
Optimizer is: adadelta, activation is: sigmoid
R-squared: -1.5286926740296702
Mean Squared Error: 710221874.8547323
Mean Absolute Error: 20720.914043151188
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adagrad, activation is: relu
R-squared: -1.3956448906365018
Mean Squared Error: 672853377.2364829
Mean Absolute Error: 20169.322916393507
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adagrad, activation is: tanh
R-squared: -1.5266740055860235
Mean Squared Error: 709654901.0577655
Mean Absolute Error: 20707.237024909573
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: adagrad, activation is: sigmoid
R-squared: -1.5271998478436548
Mean Squared Error: 709802591.8696733
Mean Absolute Error: 20710.806105742777
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
Optimizer is: adamax, activation is: relu
R-squared: 0.2937153290817195
Mean Squared Error: 198370813.62733173
Mean Absolute Error: 10423.289728576463
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adamax, activation is: tanh
R-squared: -1.508435680258302
Mean Squared Error: 704532389.4368405
Mean Absolute Error: 20583.176368246273
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
Optimizer is: adamax, activation is: sigmoid
R-squared: -1.5119514792345292
Mean Squared Error: 705519855.1601975
Mean Absolute Error: 20607.149611959652
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Optimizer is: nadam, activation is: relu
R-squared: 0.2873755608779296
Mean Squared Error: 200151434.14562696
Mean Absolute Error: 10476.40108580953
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
Optimizer is: nadam, activation is: tanh
R-squared: -1.5073053350000234
Mean Squared Error: 704214914.7445567
Mean Absolute Error: 20575.462928304867
---
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
Optimizer is: nadam, activation is: sigmoid
R-squared: -1.5077022384751526
Mean Squared Error: 704326391.1343678
Mean Absolute Error: 20578.17171431561
---